### ISSUE TITLE
Extended categories: blog import fails if some not existing in bCMS category is assigned to blog

### ISSUE THREAD

**Issue by daivabrazukaite** [devbridge/BetterCMS#1231]
I chosen to import blog post xml, which contained category with not existing in bCMS title/id information  + one blog post with same category assigned to it. Trying to import such a blog post, error was received. 

Info from logs:
2015-02-20 16:07:08.1200 Failed to execute command ImportBlogPostsCommand. Request data: BetterCms.Module.Blog.ViewModels.Blog.ImportBlogPostsViewModel, CreateRedirects: False, BlogPosts.Count: 1. 
could not execute batch command.[SQL: SQL not available] NHibernate.Exceptions.GenericADOException: could not execute batch command.[SQL: SQL not available] ---> System.Data.SqlClient.SqlException: Cannot insert the value NULL into column 'CategoryTreeId', table 'BetterCmsDemoStaging.bcms_root.Categories'; column does not allow nulls. INSERT fails.
The statement has been terminated.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at System.Data.SqlClient.SqlCommand.ExecuteBatchRPCCommand()
   at System.Data.SqlClient.SqlCommandSet.ExecuteNonQuery()
   at NHibernate.AdoNet.SqlClientSqlCommandSet.ExecuteNonQuery()
   at NHibernate.AdoNet.SqlClientBatchingBatcher.DoExecuteBatch(IDbCommand ps)
   --- End of inner exception stack trace ---
   at NHibernate.AdoNet.SqlClientBatchingBatcher.DoExecuteBatch(IDbCommand ps)
   at NHibernate.AdoNet.AbstractBatcher.ExecuteBatchWithTiming(IDbCommand ps)
   at NHibernate.AdoNet.AbstractBatcher.ExecuteBatch()
   at NHibernate.Engine.ActionQueue.ExecuteActions(IList list)
   at NHibernate.Engine.ActionQueue.ExecuteActions()
   at NHibernate.Event.Default.AbstractFlushingEventListener.PerformExecutions(IEventSource session)
   at NHibernate.Event.Default.DefaultFlushEventListener.OnFlush(FlushEvent event)
   at NHibernate.Impl.SessionImpl.Flush()
   at NHibernate.Transaction.AdoTransaction.Commit()
   at BetterCms.Core.DataAccess.DataContext.DefaultUnitOfWork.Commit()
   at BetterCms.Module.Blog.Services.DefaultBlogMLService.ImportBlogs(BlogMLBlog blogPosts, List`1 modifications, IPrincipal principal, Boolean createRedirects)
   at BetterCms.Module.Blog.Commands.ImportBlogPosts.ImportBlogPostsCommand.Execute(ImportBlogPostsViewModel request)
   at BetterCms.Module.Root.Mvc.CommandHandler.ExecuteCommand[TRequest,TResponse](ICommand`2 command, TRequest request)
Cannot insert the value NULL into column 'CategoryTreeId', table 'BetterCmsDemoStaging.bcms_root.Categories'; column does not allow nulls. INSERT fails.
The statement has been terminated. System.Data.SqlClient.SqlException (0x80131904): Cannot insert the value NULL into column 'CategoryTreeId', table 'BetterCmsDemoStaging.bcms_root.Categories'; column does not allow nulls. INSERT fails.
The statement has been terminated.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at System.Data.SqlClient.SqlCommand.ExecuteBatchRPCCommand()
   at System.Data.SqlClient.SqlCommandSet.ExecuteNonQuery()
   at NHibernate.AdoNet.SqlClientSqlCommandSet.ExecuteNonQuery()
   at NHibernate.AdoNet.SqlClientBatchingBatcher.DoExecuteBatch(IDbCommand ps)
ClientConnectionId:0aa542b6-4f85-4a20-93f5-8fff98393dde
Error Number:515,State:2,Class:16

**Comment by smikulenas** [comment]
Categories export/import functionality disabled (#1235).

**Comment by smikulenas** [comment]
Update available from 1.10.0-beta7+

**Comment by daivabrazukaite** [comment]
I do not think that current export is correct as if blog has assigned category, this category id is included under blog details, but trying to import same just exported file import fails because of this. So, please do not add assigned categories to blog export xml under blog details too.

**Comment by JuliusSenkus** [comment]
Fix available from version 1.10.3-beta7+

**Comment by JuliusSenkus** [comment]
Added functionality that only related categories with selected blogs are imported. Fix available from version 1.10.3-beta9+

**Comment by daivabrazukaite** [comment]
issues related with categories are placed under #1235. Additionally no issues found, so this one can be closed.
