### ISSUE TITLE
Search in Contents include MetaKeyword text

### ISSUE THREAD

**Issue by MrHarry01** [devbridge/BetterCMS#1284]
Hi i am getting this while searching with in contents including Meta Keyword search

2015-08-11 13:00:03.5844 Starting Lucene Index Source Watcher.
2015-08-11 13:00:03.5844 Starting Lucene Content Indexing Robot.
2015-08-11 13:00:13.9795 Lucene Index Source Watcher finished looking for new sources.
2015-08-11 13:00:41.4499 Lucene web crawler: Failed to fetch page by url /articles/august-11th-article/.
The remote server returned an error: (500) Internal Server Error. System.Net.WebException: The remote server returned an error: (500) Internal Server Error.
   at System.Net.HttpWebRequest.GetResponse()
   at BetterCMS.Module.LuceneSearch.Services.WebCrawlerService.DefaultWebCrawlerService.FetchPage(String url)
2015-08-11 13:00:58.2053 Lucene web crawler: Failed to fetch page by url /Help/eleven/.
The remote server returned an error: (500) Internal Server Error. System.Net.WebException: The remote server returned an error: (500) Internal Server Error.
   at System.Net.HttpWebRequest.GetResponse()
   at BetterCMS.Module.LuceneSearch.Services.WebCrawlerService.DefaultWebCrawlerService.FetchPage(String url)
2015-08-11 13:01:16.6070 Starting Lucene Content Indexing Robot.

**Comment by JuliusSenkus** [comment]
Hi, these errors are received when pages are not accessible, so they are simply excluded from search, this is normal behavior, and what do you mean by "include MetaKeyword text"?
