### ISSUE TITLE
Markdown: error trying to save markdown

### ISSUE THREAD

**Issue by daivabrazukaite** [devbridge/BetterCMS#1387]
Create/edit page/blog -> add Markdown -> enter name AND content -> save (no matter as draft or published): error. Same with saving already added markdown with some content.

Error from logs:
2015-10-28 09:06:47.0954 Failed to execute command SavePageHtmlContentCommand. Request data: BetterCms.Module.Pages.Command.Content.SavePageHtmlContent.SavePageHtmlContentCommandRequest. 
Could not load file or assembly 'MarkdownSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified. System.IO.FileNotFoundException: Could not load file or assembly 'MarkdownSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
File name: 'MarkdownSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'
   at BetterCms.Module.Pages.Helpers.MarkdownConverter.ToHtml(String markdown)
   at BetterCms.Module.Pages.Command.Content.SavePageHtmlContent.SavePageHtmlContentCommand.Execute(SavePageHtmlContentCommandRequest request)
   at BetterCms.Module.Root.Mvc.CommandHandler.ExecuteCommand[TRequest,TResponse](ICommand`2 command, TRequest request)

**Comment by smikulenas** [comment]
Fix available from 1.11.0-beta07+
