### ISSUE TITLE
Child widget options: exception trying to save widget/content after child widget options modal with image or folder option was opened

### ISSUE THREAD

**Issue by daivabrazukaite** [devbridge/BetterCMS#1431]
Pre-conditions: there is widget1 that contains option with type "Image Url" or/and "Images folder" (no matter if value will be assigned or not).
Create/edit widget2 (or page html content) -> insert widget1 -> open child widget options edit modal (double click on inserted widget or right mouse click and choose "Edit widget options") -> close child options modal -> save (no matter as draft or published): Sorry. Internal server error occured. Please retry later or contact administrator.

Exception from logs:
2015-11-17 11:36:36.0415 Failed to execute command SaveHtmlContentWidgetCommand. Request data: BetterCms.Module.Pages.Command.Widget.SaveWidget.SaveWidgetCommandRequest`1[BetterCms.Module.Pages.ViewModels.Widgets.EditHtmlContentWidgetViewModel]. 
Unable to cast object of type 'BetterCms.Module.Root.ViewModels.Option.CustomOptionViewModel' to type 'BetterCms.Module.Root.Models.CustomOption'. System.InvalidCastException: Unable to cast object of type 'BetterCms.Module.Root.ViewModels.Option.CustomOptionViewModel' to type 'BetterCms.Module.Root.Models.CustomOption'.
   at BetterCms.Module.Root.Models.ChildContentOption.BetterCms.Core.DataContracts.IOption.set_CustomOption(ICustomOption value)
   at BetterCms.Module.Root.Services.DefaultOptionService.SaveOptionValues[TEntity](IEnumerable`1 optionViewModels, IEnumerable`1 optionValues, Func`1 entityCreator, Func`1 translationEntityCreator)
   at BetterCms.Module.Root.Services.DefaultOptionService.SaveChildContentOptions(Content content, IList`1 viewModels, ContentStatus requestedStatus)
   at BetterCms.Module.Pages.Services.DefaultWidgetService.SaveHtmlContentWidget(EditHtmlContentWidgetViewModel model, IList`1 childContentOptionValues, HtmlContentWidget& widget, HtmlContentWidget& originalWidget, Boolean treatNullsAsLists, Boolean createIfNotExists)
   at BetterCms.Module.Pages.Command.Widget.SaveWidget.SaveHtmlContentWidgetCommand.Execute(SaveWidgetCommandRequest`1 request)
   at BetterCms.Module.Root.Mvc.CommandHandler.ExecuteCommand[TRequest,TResponse](ICommand`2 command, TRequest request)

**Comment by mantas-janulionis** [comment]
Fixed in version 1.11.0-beta11+
