### ISSUE TITLE
Widget child options: it is not possible to save widget if its child widget option for default language is changed

### ISSUE THREAD

**Issue by daivabrazukaite** [devbridge/BetterCMS#1437]
Pre-conditions: there is widget1 with at least one option assigned
Create widget2 -> insert widget1 into its content -> open child widget options -> choose language1 (! language1 <> Default language) -> set "use Default" = No -> close options -> save and <b>publish</b> widget2 -> open widget2 for edit -> open child widget options -> set "use Default" = No for default language -> close options -> save as <b>draft</b> widget2 -> open widget2 for edit once more -> save and <b>publish</b>: error will be received.

Exception from logs:
2015-11-17 16:36:12.6459 Failed to execute command SaveHtmlContentWidgetCommand. Request data: BetterCms.Module.Pages.Command.Widget.SaveWidget.SaveWidgetCommandRequest`1[BetterCms.Module.Pages.ViewModels.Widgets.EditHtmlContentWidgetViewModel]. 
could not execute batch command.[SQL: SQL not available] NHibernate.Exceptions.GenericADOException: could not execute batch command.[SQL: SQL not available] ---> System.Data.SqlClient.SqlException: Violation of UNIQUE KEY constraint 'UX_Cms_ChildContentOptionTranslations_ChildContentOption_Language'. Cannot insert duplicate key in object 'bcms_root.ChildContentOptionTranslations'. The duplicate key value is (e3f66ba8-2ff7-4d68-8bd2-a55301118957, 8da5405f-11ee-43b7-874e-a3b500f40b48, <NULL>).
The statement has been terminated.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at System.Data.SqlClient.SqlCommand.ExecuteBatchRPCCommand()
   at System.Data.SqlClient.SqlCommandSet.ExecuteNonQuery()
   at NHibernate.AdoNet.SqlClientSqlCommandSet.ExecuteNonQuery()
   at NHibernate.AdoNet.SqlClientBatchingBatcher.DoExecuteBatch(IDbCommand ps)
   --- End of inner exception stack trace ---
   at NHibernate.AdoNet.SqlClientBatchingBatcher.DoExecuteBatch(IDbCommand ps)
   at NHibernate.AdoNet.AbstractBatcher.ExecuteBatchWithTiming(IDbCommand ps)
   at NHibernate.AdoNet.AbstractBatcher.ExecuteBatch()
   at NHibernate.Engine.ActionQueue.ExecuteActions(IList list)
   at NHibernate.Engine.ActionQueue.ExecuteActions()
   at NHibernate.Event.Default.AbstractFlushingEventListener.PerformExecutions(IEventSource session)
   at NHibernate.Event.Default.DefaultFlushEventListener.OnFlush(FlushEvent event)
   at NHibernate.Impl.SessionImpl.Flush()
   at NHibernate.Transaction.AdoTransaction.Commit()
   at BetterModules.Core.DataAccess.DataContext.DefaultUnitOfWork.Commit()
   at BetterCms.Module.Pages.Services.DefaultWidgetService.SaveHtmlContentWidget(EditHtmlContentWidgetViewModel model, IList`1 childContentOptionValues, HtmlContentWidget& widget, HtmlContentWidget& originalWidget, Boolean treatNullsAsLists, Boolean createIfNotExists)
   at BetterCms.Module.Pages.Command.Widget.SaveWidget.SaveHtmlContentWidgetCommand.Execute(SaveWidgetCommandRequest`1 request)
   at BetterCms.Module.Root.Mvc.CommandHandler.ExecuteCommand[TRequest,TResponse](ICommand`2 command, TRequest request)
Violation of UNIQUE KEY constraint 'UX_Cms_ChildContentOptionTranslations_ChildContentOption_Language'. Cannot insert duplicate key in object 'bcms_root.ChildContentOptionTranslations'. The duplicate key value is (e3f66ba8-2ff7-4d68-8bd2-a55301118957, 8da5405f-11ee-43b7-874e-a3b500f40b48, <NULL>).
The statement has been terminated. System.Data.SqlClient.SqlException (0x80131904): Violation of UNIQUE KEY constraint 'UX_Cms_ChildContentOptionTranslations_ChildContentOption_Language'. Cannot insert duplicate key in object 'bcms_root.ChildContentOptionTranslations'. The duplicate key value is (e3f66ba8-2ff7-4d68-8bd2-a55301118957, 8da5405f-11ee-43b7-874e-a3b500f40b48, <NULL>).
The statement has been terminated.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at System.Data.SqlClient.SqlCommand.ExecuteBatchRPCCommand()
   at System.Data.SqlClient.SqlCommandSet.ExecuteNonQuery()
   at NHibernate.AdoNet.SqlClientSqlCommandSet.ExecuteNonQuery()
   at NHibernate.AdoNet.SqlClientBatchingBatcher.DoExecuteBatch(IDbCommand ps)
ClientConnectionId:361bfee6-01ad-4a9d-aa71-359c75372bad
Error Number:2627,State:1,Class:14

**Comment by mantas-janulionis** [comment]
Fixed in version 1.11.0-beta11+

**Comment by daivabrazukaite** [comment]
It could be received situation then incorrect "Use Default" flag option is displayed (+ incorrect values are used while using widget as content) - see example in attachment: "use default" is displayed as Yes, even "Value" <> "Default Value"
![bcms childwidgetdefaultvalue](https://cloud.githubusercontent.com/assets/3446924/11445616/5b1b6e40-9536-11e5-9334-5c4d0d3d7cbb.jpg)

Steps are similar like described in initial problem description. Pay attention, that after you open for edit widget then it is published with draft, simply press Save&Publish and DO NOT OPEN child widget options before publishing widget

**Comment by mantas-janulionis** [comment]
Fixed in version 1.11.0-beta13+
