### ISSUE TITLE
Widget in content: exception trying to open child widget options until content with inserted widget is not saved

### ISSUE THREAD

**Issue by daivabrazukaite** [devbridge/BetterCMS#1476]
If some widget is inserted and not yet saved into content (no matter page html/markdown or some other widget html), trying to open child widget options window exception is received.
Steps: open any page -> add new html type content -> from toolbar choose to insert widget -> select any widget -> double click on inserted widget (or right click and choose "Edit widget options"): Sorry. Internal server error occured. Please retry later or contact administrator

Info from logs:
2015-12-08 13:43:50.0924 Failed to execute command GetChildContentOptionsCommand. Request data: BetterCms.Module.Pages.Command.Content.GetChildContentOptions.GetChildContentOptionsCommandRequest. 
Sequence contains no elements System.InvalidOperationException: Sequence contains no elements
   at NHibernate.Linq.DefaultQueryProvider.ExecuteQuery(NhLinqExpression nhLinqExpression, IQuery query, NhLinqExpression nhQuery)
   at NHibernate.Linq.DefaultQueryProvider.Execute(Expression expression)
   at NHibernate.Linq.DefaultQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.First[TSource](IQueryable`1 source)
   at BetterCms.Module.Pages.Command.Content.GetChildContentOptions.GetChildContentOptionsCommand.Execute(GetChildContentOptionsCommandRequest request)
   at BetterCms.Module.Root.Mvc.CommandHandler.ExecuteCommand[TRequest,TResponse](ICommand`2 command, TRequest request)

**Comment by gerbenis** [comment]
Fix will be available from v1.11.0-beta14+
